autoservisas-master/mysite/autoservice/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name='automobilis'),
    path('uzsakymai/', views.UzsakymaiListView.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>', views.UzsakymasDetailView.as_view(), name='uzsakymas'),
    path('search/', views.search, name='search'),
    path('search/<int:automobilis_id>', views.automobilis, name='automobilis'),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),
    path('manouzsakymai/', views.UzsakymaiByUserListView.as_view(), name='mano-uzsakymai'),
    path('manouzsakymai/<int:pk>', views.UzsakymaiByUserDetailView.as_view(), name='mano-uzsakymas'),
    path('manouzsakymai/naujas', views.UzsakymaiByUserCreateView.as_view(), name='naujas-uzsakymas'),
    path('manouzsakymai/<int:pk>/redaguoti', views.UzsakymaiByUserUpdateView.as_view(), name='redaguoti-mano-uzsakyma'),
    path('manouzsakymai/<int:pk>/istrinti', views.UzsakymaiByUserDeleteView.as_view(), name='istrinti-mano-uzsakyma'),
]

autoservisas-master/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('autoservice/', include('autoservice.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='autoservice/', permanent=True)),
    path('tinymce/', include('tinymce.urls')),
    path(r'^i18n/', include('django.conf.urls.i18n')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

autoservisas-master/mysite/autoservice/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import pytz
from tinymce.models import HTMLField
from PIL import Image
# import computed_property
from django.utils.translation import gettext_lazy as _

utc = pytz.UTC


class Paslauga(models.Model):
    name = models.CharField('Pavadinimas', max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Paslauga'
        verbose_name_plural = 'Paslaugos'


class Automobilio_modelis(models.Model):
    metai = models.IntegerField('Metai')
    marke = models.CharField('Markė', max_length=200)
    modelis = models.CharField('Modelis', max_length=200)
    variklis = models.CharField('Variklis', max_length=200)

    def __str__(self):
        return f"{self.metai}, {self.marke} {self.modelis}, {self.variklis}"

    class Meta:
        verbose_name = 'Automobilio modelis'
        verbose_name_plural = 'Automobilio modeliai'


class Paslaugos_kaina(models.Model):
    paslauga_id = models.ForeignKey('Paslauga', on_delete=models.SET_NULL, null=True)
    automobilis_ids = models.ManyToManyField(Automobilio_modelis)
    kaina = models.FloatField("Kaina")

    def __str__(self):
        return f"{self.paslauga_id}: {self.kaina}"

    def automobiliai(self):
        return ', '.join(f"{auto.marke} {auto.modelis}" for auto in self.automobilis_ids.all())

    automobiliai.short_description = 'Automobiliai'

    class Meta:
        verbose_name = 'Paslaugo kaina'
        verbose_name_plural = 'Paslaugų kainos'


class Automobilis(models.Model):
    savininkas = models.CharField(_('Owner'), max_length=200)
    automobilio_modelis_id = models.ForeignKey('Automobilio_modelis', verbose_name=_("Vehicle"), on_delete=models.SET_NULL, null=True)
    valstybinis_numeris = models.CharField(_('Licence plate'), max_length=200)
    vin_kodas = models.CharField(_('VIN code'), max_length=200)
    photo = models.ImageField(_('Photo'), upload_to='autos', null=True)
    aprasymas = HTMLField(_("Summary"), null=True)

    def __str__(self):
        return f"{self.savininkas}: {self.automobilio_modelis_id}, {self.valstybinis_numeris}, {self.vin_kodas}"

    class Meta:
        verbose_name = _('Vehicle')
        verbose_name_plural = _('Vehicles')


class Uzsakymas(models.Model):
    automobilis_id = models.ForeignKey('Automobilis', on_delete=models.SET_NULL, null=True)
    klientas_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    grazinimo_laikas = models.DateTimeField('Gražinimo terminas', null=True, blank=True)

    @property
    def suma(self):
        uzsakymo_eilutes = UzsakymoEilute.objects.filter(uzsakymas_id=self.id)
        suma = 0
        for eilute in uzsakymo_eilutes:
            suma += eilute.kiekis * eilute.kaina
        return suma

    def __str__(self):
        return f"{self.automobilis_id}: {self.suma}"

    # @property
    # def praejes_terminas(self):
    #     if self.grazinimo_laikas:
    #         start_time = self.grazinimo_laikas.replace(tzinfo=utc)
    #         end_time = datetime.today().replace(tzinfo=utc)
    #         print("Datos:", start_time, end_time)
    #     return self.grazinimo_laikas and end_time > start_time

    @property
    def praejes_terminas(self):
        if self.grazinimo_laikas and datetime.today().replace(tzinfo=utc) > self.grazinimo_laikas.replace(tzinfo=utc):
            return True
        return False

    class Meta:
        verbose_name = 'Užsakymas'
        verbose_name_plural = 'Užsakymai'

    STATUS = (
        ('p', 'Patvirtinta'),
        ('v', 'Vykdoma'),
        ('a', 'Atlikta'),
        ('t', 'Atšaukta'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='p',
        help_text='Statusas',
    )


class UzsakymoEilute(models.Model):
    uzsakymas_id = models.ForeignKey('Uzsakymas', related_name='eilutes', on_delete=models.SET_NULL, null=True)
    paslauga_id = models.ForeignKey('Paslauga', on_delete=models.SET_NULL, null=True)
    kiekis = models.IntegerField("Kiekis")
    kaina = models.FloatField("Kaina")
    # suma = computed_property.ComputedFloatField(compute_from='suma_calculation', null=True)

    @property
    def suma(self):
        return self.kiekis * self.kaina

    def __str__(self):
        return f"{self.paslauga_id} – {self.kiekis}: {self.kaina} {self.suma}"

    class Meta:
        verbose_name = 'Užsakymo eilutė'
        verbose_name_plural = 'Užsakymo eilutės'


class UzsakymoKomentaras(models.Model):
    uzsakymas_id = models.ForeignKey('Uzsakymas', on_delete=models.SET_NULL, null=True)
    klientas_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    komentaras = models.TextField('Komentaras', max_length=2000)

    class Meta:
        verbose_name = 'Komentaras'
        verbose_name_plural = 'Komentarai'


class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nuotrauka = models.ImageField(default="default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"


    class Meta:
        verbose_name = 'Profilis'
        verbose_name_plural = 'Profiliai'

    def save(self):
        super().save()
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)

autoservisas-master/mysite/autoservice/forms.py
from .models import Profilis
from django import forms
from django.contrib.auth.models import User

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

autoservisas-master/mysite/autoservice/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.http import HttpResponse
from .models import Paslauga, Uzsakymas, Automobilis
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfilisUpdateForm
from django.utils.translation import gettext as _

def index(request):
    paslaugu_kiekis = Paslauga.objects.count()
    atliktu_uzsakymu_kiekis = Uzsakymas.objects.filter(status__exact='a').count()
    automobiliu_kiekis = Automobilis.objects.count()

    # Papildome kintamuoju num_visits, įkeliame jį į kontekstą.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'paslaugu_kiekis': paslaugu_kiekis,
        'atliktu_uzsakymu_kiekis': atliktu_uzsakymu_kiekis,
        'automobiliu_kiekis': automobiliu_kiekis,
        'num_visits': num_visits,
    }

    # renderiname base.html, su duomenimis kintamąjame context
    return render(request, 'index.html', context=context)

def automobiliai(request):
    paginator = Paginator(Automobilis.objects.all(), 5)
    page_number = request.GET.get('page')
    paged_automobiliai = paginator.get_page(page_number)
    context = {
        'automobiliai': paged_automobiliai
    }
    return render(request, 'automobiliai.html', context=context)

def automobilis(request, automobilis_id):
    automobilis = get_object_or_404(Automobilis, pk=automobilis_id)
    return render(request, 'automobilis.html', context={'automobilis': automobilis})


def search(request):
    """
    paprasta paieška. query ima informaciją iš paieškos laukelio,
    search_results prafiltruoja pagal įvestą tekstą knygų pavadinimus ir aprašymus.
    Icontains nuo contains skiriasi tuo, kad icontains ignoruoja ar raidės
    didžiosios/mažosios.
    """
    query = request.GET.get('query')
    search_results = Automobilis.objects.filter(Q(savininkas__icontains=query) | Q(valstybinis_numeris__icontains=query) | Q(vin_kodas__icontains=query) | Q(automobilio_modelis_id__marke__icontains=query) | Q(automobilio_modelis_id__modelis__icontains=query))
    return render(request, 'search.html', {'automobiliai': search_results, 'query': query})

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('Username %(username)s already exists!' ) % {'username': username})
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %(email)s already exists!') % {'email': email})
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'register.html')

@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)

class UzsakymaiListView(generic.ListView):
    model = Uzsakymas
    context_object_name = 'uzsakymai'
    paginate_by = 5
    template_name = 'uzsakymai.html'

class UzsakymasDetailView(generic.DetailView):
    model = Uzsakymas
    template_name = 'uzsakymas.html'


class UzsakymaiByUserListView(LoginRequiredMixin, generic.ListView):
    model = Uzsakymas
    template_name = 'user_uzsakymai.html'

    def get_queryset(self):
        return Uzsakymas.objects.filter(klientas_id=self.request.user).order_by('grazinimo_laikas')

class UzsakymaiByUserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Uzsakymas
    template_name = 'user_uzsakymas.html'

class UzsakymaiByUserCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzsakymas
    fields = ['automobilis_id', 'grazinimo_laikas']
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'user_uzsakymas_form.html'

    def form_valid(self, form):
        form.instance.klientas_id = self.request.user
        return super().form_valid(form)

class UzsakymaiByUserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Uzsakymas
    fields = ['automobilis_id', 'grazinimo_laikas', 'grazinimo_laikas']
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'user_uzsakymas_form.html'


    def form_valid(self, form):
        form.instance.klientas_id = self.request.user
        return super().form_valid(form)

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.klientas_id

class UzsakymaiByUserDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Uzsakymas
    success_url = "/autoservice/manouzsakymai/"
    template_name = 'user_uzsakymas_istrinti.html'

    def test_func(self):
        uzsakymas = self.get_object()
        return self.request.user == uzsakymas.klientas_id

autoservisas-master/mysite/autoservice/templates/automobiliai.html
{% extends "base.html" %}

{% block content %}

 {% load static %}
  <h1>Automobiliai</h1>
  <p>Mūsų servise registruoti automobiliai.</p>
    {% if automobiliai %}
    <div class="row">
      {% for automobilis in automobiliai %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if automobilis.photo %}
              <img src="{{ automobilis.photo.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
                <p class="card-text"><a href="{{ automobilis.id }}">{{ automobilis.automobilio_modelis_id.marke }} {{ automobilis.automobilio_modelis_id.modelis }}</a></p>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
              <h6 class="card-subtitle mb-2 text-muted">{{ automobilis.savininkas }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{ automobilis.valstybinis_numeris }}</h6>
                <h6 class="card-subtitle mb-2 text-muted">{{ automobilis.vin_kodas }}</h6>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% else %}
      <p>Automobilių nėra.</p>
    {% endif %}
<div class="container puslapiai">
    <nav aria-label="...">
        {% if automobiliai.has_other_pages %}
            <ul class="pagination pagination-sm justify-content-end">
                {% for i in automobiliai.paginator.page_range %}
                    {% if automobiliai.number == i %}
                        <li class="page-item active">
                            <a class="page-link" href="">{{ i }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
    </nav>
</div>
{% endblock %}

autoservisas-master/mysite/autoservice/templates/automobilis.html
{% extends "base.html" %}

{% block content %}
    {% load static %}
    <div class="container">
    {% if automobilis.photo %}
      <img src="{{ automobilis.photo.url }}" class="card-img-top" alt="...">
    {% else %}
      <img src="{% static 'img/no-image.png' %}" class="card-img-top">
    {% endif %}
    <h4>{{ automobilis.automobilio_modelis_id.marke }} {{ automobilis.automobilio_modelis_id.modelis }}</h4>
    <hr/>
    <p><strong>Savininkas:</strong> {{ automobilis.savininkas }}</p>
    <p><strong>Valstybinis numeris:</strong> {{ automobilis.valstybinis_numeris }}</p>
    <p><strong>VIN kodas:</strong> {{ automobilis.vin_kodas }}</p>
    {% if automobilis.aprasymas %}
        <h3>Aprašymas:</h3>
        <p>{{ automobilis.aprasymas | safe }}</p>
        {% endif %}
    </hr>
    </br>
    </div>
{% endblock %}

autoservisas-master/mysite/autoservice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Autoservisas</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% load i18n %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#">
    <svg class="bi bi-wrench" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M.102 2.223A3.004 3.004 0 003.78 5.897l6.341 6.252A3.003 3.003 0 0013 16a3 3 0 10-.851-5.878L5.897 3.781A3.004 3.004 0 002.223.1l2.141 2.142L4 4l-1.757.364L.102 2.223zm13.37 9.019L13 11l-.471.242-.529.026-.287.445-.445.287-.026.529L11 13l.242.471.026.529.445.287.287.445.529.026L13 15l.471-.242.529-.026.287-.445.445-.287.026-.529L15 13l-.242-.471-.026-.529-.445-.287-.287-.445-.529-.026z" clip-rule="evenodd"/>
    </svg>
    Autoservisas</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Pradžia</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'automobiliai' %}">Automobiliai</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'uzsakymai' %}">Užsakymai</a>
        </li>
      </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
              <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
              </svg>
            {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mano-uzsakymai'%}">Mano užsakymai</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'naujas-uzsakymas'%}?next=/autoservice">{% trans "New" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Atsijungti</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
          {% endif %}
        </ul>

      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.0 }}
          </option>
          {% endfor %}
        </select>
      </form>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="{% blocktrans %}Search{% endblocktrans %}" aria-label="Search" name="query">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
      </form>
    </div>
  </div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>


  {% comment %} <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Pradžia</a></li>
          <li><a href="{% url 'books' %}">Visos knygos</a></li>
          <li><a href="{% url 'authors' %}">Visi autoriai</a></li>
        </ul>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <input name="query" class="form-control" type="text" placeholder="Paieška">
            </form>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div> {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

autoservisas-master/mysite/autoservice/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Autoservice" %}</h1>
  <p>{% trans "Welcome to Autoservice!" %}</p>
  <p>{% trans "Autoservice statistics:" %}</p>
  <ul>
    <li><strong>{% trans "Services:" %}</strong> {{ paslaugu_kiekis }}</li>
    <li><strong>{% trans "Orders done:" %}</strong> {{ atliktu_uzsakymu_kiekis }}</li>
    <li><strong>{% trans "Vehicles:" %}</strong> {{ automobiliu_kiekis }}</li>
    <p>{% trans "Your visits" %}: {{ num_visits }}.</p>
  </ul>
{% endblock %}

autoservisas-master/mysite/autoservice/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if automobiliai %}
  <ul>
    {% for auto in automobiliai %}
      <li>
        <a href="{{ auto.id }}">{{ auto }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

autoservisas-master/mysite/autoservice/templates/user_uzsakymai.html
{% extends "base.html" %}

{% block content %}
    <h1>Mano užsakymai</h1>

    {% if uzsakymas_list %}
      {% for uzsakymas in uzsakymas_list %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2">{{ uzsakymas.klientas_id }}</a>
              <small class="text-muted">{{ uzsakymas.grazinimo_laikas|date:"Y-m-d, f" }}</small>
            </div>
            <p class="article-content">{{ uzsakymas.automobilis_id}}</p>
              <p class="card-text"><a href="{{ uzsakymas.id }}">Peržiūrėti</a></p>
          </div>
        </article>
        <hr>
      {% endfor %}
    {% else %}
      <p>Neturite užsakymų.</p>
    {% endif %}
{% endblock %}

autoservisas-master/mysite/autoservice/templates/uzsakymas.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
    <p><strong>Automobilis:</strong> {{ uzsakymas.automobilis_id }}</p>
    <p><strong>Suma:</strong> {{ uzsakymas.suma }}</p>
    <h6 class="card-subtitle mb-2 text-muted">{{ uzsakymas.get_status_display }}</h6>
    </hr>
    </br>
    </div>
<div style="margin-left:20px;margin-top:20px">
    <h4>Darbai:</h4>
    {% for eilute in uzsakymas.eilutes.all %}
      <hr>
        <p><strong>Paslauga:</strong> {{ eilute.paslauga_id }}  <strong>Kiekis:</strong> {{ eilute.kiekis }}<strong>    Kaina:</strong> {{ eilute.kaina }} <strong>    Suma:</strong> {{ eilute.suma }}</p>
    {% endfor %}
  </div>

</br>
  <h4>Komentarai:</h4>
  {% if uzsakymas.uzsakymokomentaras_set.all %}
    {% for komentaras in uzsakymas.uzsakymokomentaras_set.all %}
      <hr>
      <strong>{{ komentaras.klientas_id }}</strong>, <em>{{ komentaras.date_created}}</em>
      <p>{{ komentaras.komentaras }}</p>
    {% endfor %}
  {% else %}
    <p>Užsakymas neturi komentarų</p>
  {% endif %}

{% endblock %}